apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: 4kube-dev
  labels:
    app: mysql
    storage: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
   - ReadWriteMany
   - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql