apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prestashop
  namespace: 4kube-dev
  labels:
    app: prestashop
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-prestashop